baseURL: "https://franek.chicour.net"
title: "::franek::"
theme:
  - hugo-PaperMod
publishDir: "public"
defaultContentLanguage: fr

permalinks:
  posts: "/post/:year/:month/:title/"

markup:
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: unknown

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "::franek::"
    description: ""
    author: Franek
    # author: ["Me", "You"] # multiple authors

    #images: "<link or path of image for opengraph, twitter-cards>"

    ShowReadingTime: false
    ShowShareButtons: false
    comments: false
    defaultTheme: light
    disableThemeToggle: true
    disableSpecial1stPost: false

    #assets:
        #favicon: "https://franek.chicour.net/public/logo-franek.png"
        #favicon16x16: "https://franek.chicour.net/public/logo-franek.png"
        #favicon32x32: "https://franek.chicour.net/public/logo-franek.png"
        #apple_touch_icon: "https://franek.chicour.net/public/logo-franek.png"
        #safari_pinned_tab: "https://franek.chicour.net/public/logo-franek.png"

    label:
        text: ""
        icon: /public/logo-franek.png
        iconHeight: 35

    # home-info mode
    homeInfoParams:
        Title: "\U0001F44B"
        Content: "Je partage ici quelques bafouilles sur la technologie, le vélo, ou mes coups de coeur (musique, lecture)."

    socialIcons:
        - name: bluesky
          url: "https://bsky.app/profile/franek.chicour.net"
        - name: github
          url: "https://github.com/franek"
        - name: mastodon
          url: "https://pouet.chapril.org/@franek"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

taxonomies:
    tag: tags
    
menu:
    main:
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 10
        - identifier: archives
          name: Archives
          url: /archive/
          weight: 20
        - identifier: search
          name: Recherche
          url: /search/
          weight: 30
        - identifier: RSS
          name: RSS
          url: /feed/rss2
          weight: 40

outputs:
    home:
        - html
        - rss
        - atom

# For compatibility with dotclear (old blog system), redefine feed URI to /feed/atom
mediaTypes:
  application/rss+xml:
    suffixes: 
      - ""
    delimiter: ""
  application/atom+xml:
    suffixes: 
      - ""
    delimiter: ""

outputFormats:
  rss:
    mediatype: "application/rss+xml"
    baseName: "feed/rss2"
  atom:
    mediatype: "application/atom+xml"
    baseName: "feed/atom"
